# General
title:          Emanuele Frasca
description:    Computer Engineering, Artificial Intelligence
url:            https://noostale.github.io/
baseurl:        /emanuelefrasca

# Navigation
permalink:      /:slug

# Minify CSS
sass:
  style: compressed
  sourcemap: never

# Contact
author:
  name: César Ferradas
  contacts:
    - name: GitHub
      url: https://github.com/noostale
      handle: noostale
    - name: LinkedIn
      url: https://www.linkedin.com/in/emanuelefrasca/
      handle: Emanuele Frasca

# Gems
plugins:
  - jekyll-feed
  - jekyll-sitemap

highlighter: rouge

exclude:
  - new_post.sh
